### ISSUE TITLE
Shilly goes offline and then re-appears

### ISSUE THREAD

**Issue by BlakeAM** [abrkn/shilly#69]
1st occurred ~1.5 hours ago and just happened again as the issue was opened.

**Comment by abrkn** [comment]
Sounds like a crash. I'll have a look at the logs.

**Comment by abrkn** [comment]
```
2018-01-19T19:31:24.536848+00:00 heroku[bot.1]: Starting process with command `npm start`
2018-01-19T19:31:25.290781+00:00 heroku[bot.1]: State changed from starting to up
2018-01-19T19:31:27.500810+00:00 app[bot.1]:
2018-01-19T19:31:27.500830+00:00 app[bot.1]: > shilly@1.0.45 start /app
2018-01-19T19:31:27.500831+00:00 app[bot.1]: > node -r panik index.js
2018-01-19T19:31:27.500833+00:00 app[bot.1]:
2018-01-19T19:31:27.069145+00:00 app[bot.1]: [heroku-exec] Starting
2018-01-19T19:31:29.273513+00:00 app[bot.1]: Waiting for Discord to connect...
2018-01-19T19:31:29.274508+00:00 app[bot.1]: (node:61) ExperimentalWarning: The http2 module is an experimental API.
2018-01-19T19:31:29.477313+00:00 app[bot.1]: Discord connected
2018-01-19T19:31:29.800129+00:00 app[bot.1]: Error: Service Unavailable
2018-01-19T19:31:29.800142+00:00 app[bot.1]:     at Request.callback (/app/node_modules/superagent/lib/node/index.js:699:13)
2018-01-19T19:31:29.800144+00:00 app[bot.1]:     at IncomingMessage.parser (/app/node_modules/superagent/lib/node/index.js:903:18)
2018-01-19T19:31:29.800148+00:00 app[bot.1]:     at emitNone (events.js:111:20)
2018-01-19T19:31:29.800149+00:00 app[bot.1]:     at IncomingMessage.emit (events.js:208:7)
2018-01-19T19:31:29.800151+00:00 app[bot.1]:     at endReadableNT (_stream_readable.js:1055:12)
2018-01-19T19:31:29.800152+00:00 app[bot.1]:     at _combinedTickCallback (internal/process/next_tick.js:138:11)
2018-01-19T19:31:29.800153+00:00 app[bot.1]:     at process._tickCallback (internal/process/next_tick.js:180:9)
2018-01-19T19:31:29.815191+00:00 app[bot.1]: npm ERR! code ELIFECYCLE
2018-01-19T19:31:29.815689+00:00 app[bot.1]: npm ERR! errno 1
2018-01-19T19:31:29.817512+00:00 app[bot.1]: npm ERR! shilly@1.0.45 start: `node -r panik index.js`
2018-01-19T19:31:29.817713+00:00 app[bot.1]: npm ERR! Exit status 1
2018-01-19T19:31:29.817997+00:00 app[bot.1]: npm ERR!
2018-01-19T19:31:29.818195+00:00 app[bot.1]: npm ERR! Failed at the shilly@1.0.45 start script.
2018-01-19T19:31:29.818381+00:00 app[bot.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2018-01-19T19:31:29.831622+00:00 app[bot.1]:
2018-01-19T19:31:29.831821+00:00 app[bot.1]: npm ERR! A complete log of this run can be found in:
2018-01-19T19:31:29.831960+00:00 app[bot.1]: npm ERR!     /app/.npm/_logs/2018-01-19T19_31_29_826Z-debug.log
2018-01-19T19:31:29.915065+00:00 heroku[bot.1]: State changed from up to crashed
2018-01-19T19:31:29.899283+00:00 heroku[bot.1]: Process exited with status 1
```

**Comment by abrkn** [comment]
It's hard to see from the logs what is crashing. It's definitely a lookup of some external REST API. I'll have to go through them all and make sure they fail more gracefully.
